// Action Types
export const LOGIN_CITIZEN_REQUEST = "LOGIN_CITIZEN_REQUEST";
export const LOGIN_CITIZEN_SUCCESS = "LOGIN_CITIZEN_SUCCESS";
export const LOGIN_CITIZEN_FAILURE = "LOGIN_CITIZEN_FAILURE";
