// Action Types
export const CITIZEN_SIGNUP_REQUEST = 'CITIZEN_SIGNUP_REQUEST';
export const CITIZEN_SIGNUP_SUCCESS = 'CITIZEN_SIGNUP_SUCCESS';
export const CITIZEN_SIGNUP_FAILURE = 'CITIZEN_SIGNUP_FAILURE';export const LOGIN_CITIZEN_REQUEST = "LOGIN_CITIZEN_REQUEST";
export const LOGIN_CITIZEN_SUCCESS = "LOGIN_CITIZEN_SUCCESS";
export const LOGIN_CITIZEN_FAILURE = "LOGIN_CITIZEN_FAILURE";
